name: "vqgan_3d"
save_dir: "./logs"
checkpoint_dir: "./checkpoints/vqgan_3d"
precision: 16
max_epochs: 5000
check_val_every_n_epoch: 10
strategy: "ddp_find_unused_parameters_true"
batch_size: 2
num_workers: 4
gradient_clip_val: 0.0001   # 梯度裁剪值

model:
  lr: 0.0003                # 学习率
  startd_step: 15000        # 判别器开始训练的步数
  # loss权重
  gan_feat_weight: 0.1     # GAN 特征损失权重
  adv_weight: 0.01         # 对抗损失权重
  recon_weight: 1.0        # 重建损失权重
  perceptual_weight: 0.1   # 感知损失权重
  # 模型参数
  in_channels: 3           # 输入通道数
  out_channels: 3          # 输出通道数
  model_type: "3d"         # 模型类型
  basedim: 32              # 基础维度
  downdeepth: 2            # 下采样深度
  num_groups: 32           # 分组数
  # 判别器参数
  gan_type: "hinge"        # 判别器类型
  disc_channels: 64        # 判别器通道数
  disc_downdeepth: 3       # 判别器下采样深度
  # 码本参数
  embedding_dim: 8         # 编码器输出维度
  n_codes: 8192            # 码本大小
